### ISSUE TITLE
saveViewportScreenshot is not a function

### ISSUE THREAD

**Issue by knownasilya** [zinserjan/wdio-screenshot#8]
```js
var options = {
  desiredCapabilities: {
    browserName: 'chrome'
  },
  plugins: {
    'wdio-screenshot': {}
  }
};
webdriverio
  .remote(options)
  .init()
  .setViewportSize(size, false)
  .url(url)
  .pause(10000)
  //.screenshot()
  .saveViewportScreenshot('out.png')
  .then(function(res) {
    if (res.state === 'success') {
      fs.writeFile('out.png', res.value, 'base64', function(err) {
        if (err) console.error(err);
      });
    } else {
      console.log(res);
    }
  })
  .end();
```

Tried the following and got:

```no-highlight
TypeError: webdriverio.remote(...).init(...).setViewportSize(...).url(...).pause(...).saveViewportScreenshot is not a function
    at Object.<anonymous> (/Users/iradchenko/workspace/mapgeo2/tools/selenium-screenshot.js:38:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by zinserjan** [comment]
I don't use WebdriverIO in standone mode via their API, but it should work with the following:

```
var options = {
  //host: '23.236.51.188',
  desiredCapabilities: {
    browserName: 'chrome'
  }
};

var client = require('webdriverio').remote(options);
require('wdio-screenshot').init(client);

client
  .init()
  .setViewportSize(size, false)
  .url(url)
  .pause(10000)
  //.screenshot()
  .saveViewportScreenshot('out.png')
  .end();

```

Btw have a look at [WDIO Test runner](http://webdriver.io/guide/testrunner/gettingstarted.html)
